spring.application.name=demo

app.sqlite.path=./data/demo.sqlite
app.sqlite.max-result-rows=200

app.sqlite.seed-if-empty=true

# For instant reloading of templates during development
spring.thymeleaf.cache=false
